////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gen model, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package project

import "time"

//go:generate gormgen -s Project -i .
type Project struct {
	Id         int32     `json:"id" gorm:"type:int"`             //
	Title      string    `json:"title" gorm:"type:string"`       //
	Desc       string    `json:"desc" gorm:"type:string"`        //
	GitUrl     string    `json:"git_url" gorm:"type:string"`     //
	GitType    int32     `json:"git_type" gorm:"type:int"`       //
	GitBranch  string    `json:"git_branch" gorm:"type:string"`  //
	ClusterIds string    `json:"cluster_ids" gorm:"type:string"` //
	CreatedAt  time.Time `json:"created_at" gorm:"type:time"`    //
	UpdatedAt  time.Time `json:"updated_at" gorm:"type:time"`    //
}

func (_ *Project) TableName() string {
	return "projects"
}
