////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gen model, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package role

//go:generate gormgen -s Role -i .
type Role struct {
	Id       int32  `json:"id" gorm:"type:int"`           //
	RoleName string `json:"role_name" gorm:"type:string"` //
	RoleDesc string `json:"role_desc" gorm:"type:string"` //
}

func (_ *Role) TableName() string {
	return "roles"
}
