////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gen model, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package role

//go:generate deploy_server gormgen -s Role -i .
type Role struct {
	Id       int32  `json:"id"`        //
	RoleName string `json:"role_name"` //
	RoleDesc string `json:"role_desc"` //
}

func (_ *Role) TableName() string {
	return "roles"
}
