////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gen model, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package config

//go:generate deploy_server gormgen -s Config -i .
type Config struct {
	Id        int32  `json:"id"`         //主键
	Title     string `json:"title"`      //配置的介绍
	Key       string `json:"key"`        //配置的Key
	Value     string `json:"value"`      //配置的值
	Type      int32  `json:"type"`       //配置类型[1=>数值,2=>文本,3=>JSON]
	CreatedAt int32  `json:"created_at"` //创建时间
	UpdatedAt int32  `json:"updated_at"` //更新时间
	IsDelete  int32  `json:"is_delete"`  //是否删除
}

func (_ *Config) TableName() string {
	return "sys_configs"
}
