////////////////////////////////////////////////////////////
// THIS FILE IS AUTO GENERATED by gen model, DON'T EDIT IT //
//        ANY CHANGES DONE HERE WILL BE LOST              //
////////////////////////////////////////////////////////////

package user

//go:generate deploy_server gormgen -s User -i .
type User struct {
	Id       int32  `json:"id"`       //
	Name     string `json:"name"`     //
	Password string `json:"password"` //
	Role     string `json:"role"`     //
}

func (_ *User) TableName() string {
	return "users"
}
